### ISSUE TITLE
Cannot find module './nvm-help'

### ISSUE THREAD

**Issue by neilmalgaonkar** [brianloveswords/nvm#2]
Hi Brian,

today I installed nvm on windows machine with npm install -g nvm. it installed perfectly. so when I try nvm from command line i get the following error 

module.js:340
    throw err;
          ^
Error: Cannot find module './nvm-help'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\neil\AppData\Roaming\npm\node_modules\nvm\bi
n\nvm:24:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

I debug the code and I found , that when i envoke nvm from command line without any parameter  code tries to load nvm-help file which it dosen't finds.

could you help me ?

**Comment by seiyria** [comment]
This tripped me up as well. Quite annoying.

**Comment by faceleg** [comment]
Yes this should be removed.

**Comment by brianloveswords** [comment]
Yep, everyone expects this package to be the *real* `nvm` which is why I stopped maintaining it. When I first named this, I didn't know about the *real* nvm, and we actually have different philosophies about how this sorta stuff should work. I gave ownership of the NPM package over to the current maintainer of `nvm` and whenever he has it ready to be npm publishable, that's gonna happen and be 1.0.0. Sorry for the confusion – I wish I did proper research at the time and never named this thing `nvm`, it's been the worst having to deal with people super mad at me all the time for doing so :(

**Comment by faceleg** [comment]
@brianloveswords I'm not mad! I love you for contributing code!

**Comment by NateFerrero** [comment]
To be fair, I think @fresheneesz was the only one who was actually mad. We all love open source, unfortunately sometimes decisions have to be made for the greater good. This is one of those times. The other nvm has a much larger userbase. If you have a unique concept and would like to get it out there, I would suggest coming up with a new name at this point and I'm sure if the ideas are good you can drum up a community around it. Never stop open source coding :+1:

**Comment by fresheneesz** [comment]
@brianloveswords Sorry if my comment gave you strife! I appreciate the effort you've made to correct the situtation, tho I could suggest taking what is currently there off npm until the other nvm finds time to push theirs on

**Comment by reggi** [comment]
Just installed this by accident over the real `nvm` super confusing. Thanks for the explanation @brianloveswords!!

**Comment by eduardoinnorway** [comment]
lol, 2015 and I did the same misstake, @brianloveswords how write about this in the Readme?

**Comment by flyswatter** [comment]
*brianloveswords wrote:*
```
 everyone expects this package to be the real nvm which is why I stopped maintaining it.
```

@brianloveswords If you've gone so far as to stop maintaining this project, maybe it would be time to actually transfer the npm namespace to the `nvm` everyone knows and uses.  What with the `iojs` merge, and now even `lodash` and `underscore` close to merging, perhaps 'tis the season to peacefully resolve awkward open-source issues.

**Comment by eduardoinnorway** [comment]
I agree with him ^
